#research_task:
  #description: >
    #Conduct a thorough research about {topic}
    #Make sure you find any interesting and relevant information given
    #the current year is {current_year}.
  #expected_output: >
    #A list with 10 bullet points of the most relevant information about {topic}
  #agent: researcher

#reporting_task:
  #description: >
    #Review the context you got and expand each topic into a full section for a report.
    #Make sure the report is detailed and contains any and all relevant information.
  #expected_output: >
    #A fully fledged report with the main topics, each with a full section of information.
    #Formatted as markdown without '```'
  #agent: reporting_analyst


monitor_task:
  description: >
    Identificar o que são queries dentro dos textos recebidos
    Identificar as queries que foram feitas uma em seguida da outra, ou seja, se estão relacionadas 
    Coletar queries de atividades recentes e repassá-los ao analista.

  agent: monitor_agent

analyst_task:
    description: >
      Analisar as queries e identificar possíveis ameaças
      Identificar padrões suspeitos como OR 1=1, DROP TABLE, GRANT ALL
      Analisar volume de consultas (muitos SELECTs seguidos podem ser exfiltração)
      Identificar usuários acessando dados que não deveriam
      Monitorar tentativas de login repetidas com senhas diferentes
      E identificar muitos outros tipos de ameaças possíveis

    agent: analyst_agent

executor_task:
  description: >
    Com base nos achados do analista, tomar ações de mitigação

  agent: executor_agent